# Generated by Django 4.1.3 on 2023-05-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_ctg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cervice_category', to='main.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='services',
            field=models.ManyToManyField(blank=True, to='main.services'),
        ),
    ]
