# Generated by Django 4.1.3 on 2023-06-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_serviceimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceimages',
            old_name='image',
            new_name='img',
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='services',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='service'),
        ),
    ]
