# Generated by Django 4.1.3 on 2023-06-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_image_serviceimages_img_category_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceimages',
            old_name='product',
            new_name='service',
        ),
    ]
